receivers:
  filelog:
    include: ["/var/log/app/*.log"]
    start_at: beginning
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.timestamp
          layout: '%Y-%m-%dT%H:%M:%SZ'

processors:
  batch: {}

exporters:
  otlp:
    endpoint: apm-server.default.svc.cluster.local:8200
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [otlp]
