name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Print Go version & environment
      run: |
        go version
        go env

    - name: List repo contents
      run: |
        ls -Rla .

    - name: Ensure dependencies are correct
      run: |
        go mod tidy
        go mod verify

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
